Use two new sections for ruff: `typing` and `testing`
- Everything related to the `typing` module is grouped
  in the second import section. Typing is just there
  for verification purposes, it's not a logic module
  like a local or system module that is used
  in functions or algorithms.
- And all `pytest` imports are added in a third
  section just after `typing`.
- `future` imports are in the first section to avoid
  this error during checks:
  """
  SyntaxError: from __future__ imports must occur at the beginning of the file
  """

Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.tech>