Fix wait_for behavior (#224)
* Make `wait_for` more accurate

- The old version does not take into account the execution time of `fn`.
  So instead of waiting 2 minutes (using the default timeout_secs delay),
  we can end up with much longer delays like 4 minutes.

- And for basic functions, the timeout is not respected. For example if I patch common.py like that:

```
def toto():
  return False

wait_for(toto, timeout_secs=10)
```

Run wait_for call:
```
> time ./common.py
Traceback (most recent call last):
  File "/home/ronan/Projets/sm/./test.py", line 27, in <module>
    wait_for(toto, timeout_secs=10)
  File "/home/ronan/Projets/sm/./test.py", line 18, in wait_for
    raise TimeoutError(
Exception: Timeout reached while waiting for fn call to yield True (10).

real    0m8,040s
user    0m0,021s
sys     0m0,016s
```

Signed-off-by: Ronan Abhamon <ronan.abhamon@vates.tech>
Co-authored-by: Gael Duperrey <gduperrey@vates.tech>