lvmohba: Add tests to Broken tests
This test was recently introduced but seems not yet supported by CI,
due to hardware requierements (to be investigated).

Observed issue is:

```
tests/storage/lvmohba/test_lvmohba_sr.py::TestLVMOHBASRCreateDestroy::test_create_and_destroy_sr[qcow2] ERROR [ 21%]

    @pytest.fixture(scope='package')
    def lvmohba_device_config():
>       return config.sr_device_config("LVMOHBA_DEVICE_CONFIG")
tests/storage/lvmohba/conftest.py:11:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

datakey = 'LVMOHBA_DEVICE_CONFIG'

    def sr_device_config(datakey: str, *, required: list[str] = []) -> dict[str, str]:
        import data  # import here to avoid depending on this user file for collecting tests
>       config = getattr(data, datakey)
        AttributeError: module 'data' has no attribute 'LVMOHBA_DEVICE_CONFIG'
```

Signed-off-by: Philippe Coval <philippe.coval@vates.tech>