don't check the type of priv_key
it breaks the CI:

~~~
>           assert isinstance(priv_key, (pkcs7.PKCS7PrivateKeyTypes))
E           AttributeError: module 'cryptography.hazmat.primitives.serialization.pkcs7' has no attribute 'PKCS7PrivateKeyTypes'
~~~

Signed-off-by: Gaëtan Lehmann <gaetan.lehmann@vates.tech>